# baseado (copiado) do https://github.com/coderefinery/gh-pages-multibranch/blob/main/.github/workflows/test.yml
# e tambem no workflow padrão do gh pages

name: Deploy Github Pages
on:
  push:
    paths: "src/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  multipages:
    name: Test multipages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      
      - name: multipages
        uses: rkdarst/gh-pages-multibranch@dev
        if: ${{ github.event_name == 'push' }}
        with:
          directory: src
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: src/
          force_orphan: true
