# basicamente o coisa padrão do github pages de static html :P

name: Deploy to Github Pages
on:
  push:
    paths: "src/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy all branches
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 0
      
      - name: Clone all branches
        run: |
          mkdir -p src/branch
          links=""
          for branch in $(git branch -r | grep -v '\->'); do
            if [[ "$branch" == "origin/"* ]] && [[ "${branch#origin/}" != "main" ]]; then
              echo "Cloning branch ${branch}!"
              true_branch="${branch#origin/}"
              git clone -b "$true_branch" --single-branch https://github.com/pedro-escola/painel-smart-farm.git "temp"

              link="$(echo -e "\t\t\t<a href="branch/${true_branch}/index.html">${true_branch}</a>")"
              if [[ "${links}" == "" ]]; then
                links="${links}${link}"
              else
                links="$(echo -e "${links}\n${link}")"
              fi

              mv temp/src src/branch/$true_branch
              rm -rf temp/
              echo "Cloned branch ${branch}!"
            fi
          done
          perl -pi -e "s|placeholder|${links}|" src/index.html
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './src'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
