# baseado (copiado) do https://github.com/coderefinery/gh-pages-multibranch/blob/main/.github/workflows/test.yml
# e tambem no workflow padrão do gh pages

name: Deploy to Github Pages
on:
  push:
    paths: "src/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  multipages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      
      - name: Clone all branches
        run: |
          mkdir -p src/branch
          for branch in $(git branch -r | grep -v '\->'); do
            echo "Found branch ${branch}!"
            if [[ "$branch" == "origin/"* ]]; then
              true_branch="${branch#origin/}"
              git clone -b "$true_branch" --single-branch https://github.com/pedro-escola/painel-smart-farm.git "src/branch/$true_branch"
            fi
          done
          cd "$GITHUB_WORKSPACE"
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './src'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
